version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - "> 7.3.1"
  - dependency-name: pacote
    versions:
    - "> 9.5.12"
  - dependency-name: spectron
    versions:
    - "> 9.0.0"
