name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
jobs:
  ci:
    name: CI
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: exit 0
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: deps-${{ hashFiles('**/package.json') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.npm
          key: deps-${{ hashFiles('**/package.json') }}
          restore-keys: |
            deps-
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
